// This file is auto-generated by codegen
// Do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of Phong
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const idsParam = searchParams.get('ids')

    const whereClause = idsParam
      ? { idP: { in: idsParam.split(',') } }
      : {}

    const phongs = await prisma.phong.findMany({
      where: whereClause,
      include: {
        hangPhong: true,
        trangThai: true,
      }
    })

    return NextResponse.json({
      success: true,
      data: phongs,
    })
  } catch (error) {
    console.error('Error fetching phong:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new Phong
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newPhong = await prisma.phong.create({
      data: body,
      include: {
        hangPhong: true,
        trangThai: true,
      }
    })

    return NextResponse.json(
      { success: true, data: newPhong },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating Phong:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
