// This file is auto-generated by codegen
// Do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of DoiPhong
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const idsParam = searchParams.get('ids')

    const whereClause = idsParam
      ? { idDp: { in: idsParam.split(',') } }
      : {}

    const doiPhongs = await prisma.doiPhong.findMany({
      where: whereClause,
      include: {
        cTPhieuThue: true,
        phongMoi: true,
      }
    })

    return NextResponse.json({
      success: true,
      data: doiPhongs,
    })
  } catch (error) {
    console.error('Error fetching doiPhong:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new DoiPhong
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newDoiPhong = await prisma.doiPhong.create({
      data: body,
      include: {
        cTPhieuThue: true,
        phongMoi: true,
      }
    })

    return NextResponse.json(
      { success: true, data: newDoiPhong },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating DoiPhong:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
