// This file is auto-generated by codegen
// Do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of GiaDichVu
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const idsParam = searchParams.get('ids')

    const whereClause = idsParam
      ? { idGdv: { in: idsParam.split(',') } }
      : {}

    const giaDichVus = await prisma.giaDichVu.findMany({
      where: whereClause,
      include: {
        dichVu: true,
        nhanVien: true,
      }
    })

    return NextResponse.json({
      success: true,
      data: giaDichVus,
    })
  } catch (error) {
    console.error('Error fetching giaDichVu:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new GiaDichVu
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newGiaDichVu = await prisma.giaDichVu.create({
      data: body,
      include: {
        dichVu: true,
        nhanVien: true,
      }
    })

    return NextResponse.json(
      { success: true, data: newGiaDichVu },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating GiaDichVu:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
