// This file is auto-generated by codegen
// Do not modify it directly
import { AnhHangPhong } from '@/lib/generated/prisma'

const API_URL = '/api/anh-hang-phong'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of AnhHangPhong
export async function getListAnhHangPhong(): Promise<ApiResponse<AnhHangPhong[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get list of AnhHangPhong by ids
export async function getListAnhHangPhongByIds(ids: string[]): Promise<ApiResponse<AnhHangPhong[]>> {
  try {
    const response = await fetch(`${API_URL}?ids=${ids.join(',')}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get AnhHangPhong by idAhp
export async function getAnhHangPhong(id: string): Promise<ApiResponse<AnhHangPhong>> {
  try {
    const response = await fetch(`${API_URL}/${id}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Update AnhHangPhong
export async function updateAnhHangPhong(
  id: string,
  data: Partial<Omit<AnhHangPhong, 'idAhp'>>
): Promise<ApiResponse<AnhHangPhong>> {
  try {
    const response = await fetch(`${API_URL}/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Delete AnhHangPhong
export async function deleteAnhHangPhong(id: string): Promise<ApiResponse<void>> {
  try {
    const response = await fetch(`${API_URL}/${id}`, {
      method: 'DELETE',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new AnhHangPhong
export async function createAnhHangPhong(
  data: Omit<AnhHangPhong, 'idAhp'>
): Promise<ApiResponse<AnhHangPhong>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
