// This file is auto-generated by codegen
// Do not modify it directly
import type { NhanVien, BoPhan, NhomQuyen } from '@/lib/generated/prisma'

export interface LoginRequest {
  username: string
  password: string
}

export interface RegisterRequest {
  username: string
  password: string
  email: string
  ho: string
  ten: string
  sdt?: string
  idBp?: string
  idNq?: string
}

export interface AuthResponse {
  success: boolean
  data?: {
    user: NhanVien & {
      boPhan: BoPhan
      nhomQuyen: NhomQuyen
    }
    token?: string
  }
  message?: string
}

const API_BASE = '/api/auth'

// Login
export async function login(credentials: LoginRequest): Promise<AuthResponse> {
  try {
    const response = await fetch(`${API_BASE}/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(credentials),
      credentials: 'include', // Important for cookies
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      message: error instanceof Error ? error.message : 'Login failed',
    }
  }
}

// Register
export async function register(data: RegisterRequest): Promise<AuthResponse> {
  try {
    const response = await fetch(`${API_BASE}/register`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      message: error instanceof Error ? error.message : 'Registration failed',
    }
  }
}

// Logout
export async function logout(): Promise<{ success: boolean; message?: string }> {
  try {
    const response = await fetch(`${API_BASE}/logout`, {
      method: 'POST',
      credentials: 'include',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      message: error instanceof Error ? error.message : 'Logout failed',
    }
  }
}

// Get current user
export async function getCurrentUser(): Promise<AuthResponse> {
  try {
    const response = await fetch(`${API_BASE}/me`, {
      credentials: 'include',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      message: error instanceof Error ? error.message : 'Failed to get user',
    }
  }
}
