// This file is auto-generated by codegen
// Do not modify it directly
import type { NhanVien, BoPhan, NhomQuyen } from '@/lib/generated/prisma'

export interface LoginRequest {
  username: string
  password: string
}

export interface RegisterRequest {
  username: string
  password: string
  email: string
  ho: string
  ten: string
  sdt?: string
  idBp?: string
  idNq?: string
}

export interface AuthResponse {
  success: boolean
  data?: {
    user: NhanVien & {
      boPhan: BoPhan
      nhomQuyen: NhomQuyen
    }
    token?: string
  }
  message?: string
}

const API_BASE = 'http://localhost:3000/api/auth'

// Login
export async function login(credentials: LoginRequest): Promise<AuthResponse> {
  try {
    const response = await fetch(`${API_BASE}/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(credentials),
      credentials: 'include', // Important for cookies
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      message: error instanceof Error ? error.message : 'Login failed',
    }
  }
}

// Register
export async function register(data: RegisterRequest): Promise<AuthResponse> {
  try {
    const response = await fetch(`${API_BASE}/register`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      message: error instanceof Error ? error.message : 'Registration failed',
    }
  }
}

// Logout
export async function logout(): Promise<{ success: boolean; message?: string }> {
  try {
    const response = await fetch(`${API_BASE}/logout`, {
      method: 'POST',
      credentials: 'include',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      message: error instanceof Error ? error.message : 'Logout failed',
    }
  }
}

// Get current user
export async function getCurrentUser(): Promise<AuthResponse> {
  try {
    const response = await fetch(`${API_BASE}/me`, {
      credentials: 'include',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      message: error instanceof Error ? error.message : 'Failed to get user',
    }
  }
}

// This file is auto-generated by codegen
// Do not modify it directly

// --- INTERFACES HIỆN CÓ ---
export interface LoginRequest {
  username: string
  password: string
}

export interface RegisterRequest {
  username: string
  password: string
  email: string
  ho: string
  ten: string
  sdt?: string
  idBp?: string
  idNq?: string
}

export interface AuthResponse {
  success: boolean
  data?: {
    user: NhanVien & {
      boPhan: BoPhan
      nhomQuyen: NhomQuyen
    }
    token?: string
  }
  message?: string
}

// --- INTERFACES MỚI ---

// Dùng cho fetchUserInfoById (giống AuthResponse nhưng không cần token)
export interface UserInfoResponse {
  success: boolean
  data?: {
    user: NhanVien & {
      boPhan: BoPhan
      nhomQuyen: NhomQuyen
    }
  }
  message?: string
}

export interface UserUpdateRequest {
  idNv: string // ID nhân viên
  ho?: string
  ten?: string
  email?: string
  sdt?: string
  diaChi?: string | null
  ngaySinh?: string | null
  phai?: string | null
  hinh?: string | null
}

export interface PasswordChangeRequest {
  username: string // hoặc idNv, dùng để xác định người dùng
  oldPassword: string // Mật khẩu cũ
  newPassword: string
}

export interface SimpleResponse {
  success: boolean
  message?: string
}



export async function fetchUserInfoById(idNv: string): Promise<UserInfoResponse> {
  try {
    // Giả định endpoint GET /api/user/profile/:idNv
    const response = await fetch(`${API_BASE}/update-user/${idNv}`, {
      method: 'GET', 
      // Credentials cần thiết nếu endpoint yêu cầu xác thực để xem thông tin user khác
    })
    console.log(idNv);
    // Nếu response không thành công (ví dụ: 404, 401)
    if (!response.ok) {
        const errorData = await response.json();
        return {
            success: false,
            message: errorData.message || `Lỗi HTTP: ${response.status}`,
        }
    }

    return await response.json() as UserInfoResponse
  } catch (error) {
    return {
      success: false,
      message: error instanceof Error ? error.message : 'Failed to fetch user info by ID',
    }
  }
}

/**
 * Cập nhật thông tin hồ sơ người dùng.
 * Endpoint: /api/user/user-info
 */
export async function updateUserInfo(data: UserUpdateRequest): Promise<SimpleResponse> {
  try {
    const response = await fetch(`${API_BASE}/update-user`, {
      method: 'PUT', // Dùng PUT/PATCH cho cập nhật
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
      credentials: 'include', // Gửi cookie/token để xác thực
    })
    
    if (!response.ok) {
        const errorData = await response.json();
        return {
            success: false,
            message: errorData.message || `Cập nhật thất bại (Status: ${response.status})`,
        }
    }
    
    return await response.json() as SimpleResponse
  } catch (error) {
    return {
      success: false,
      message: error instanceof Error ? error.message : 'Network error or failed to update info',
    }
  }
}

/**
 * Đổi mật khẩu người dùng.
 * Endpoint: /api/auth/change-password
 */
export async function changePassword(data: PasswordChangeRequest): Promise<SimpleResponse> {
  try {
    const response = await fetch(`${API_BASE}/update-user`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
      credentials: 'include', // Gửi cookie/token để xác thực
    })
    
    if (!response.ok) {
        const errorData = await response.json();
        return {
            success: false,
            message: errorData.message || `Đổi mật khẩu thất bại (Status: ${response.status})`,
        }
    }

    return await response.json() as SimpleResponse
  } catch (error) {
    return {
      success: false,
      message: error instanceof Error ? error.message : 'Network error or failed to change password',
    }
  }
}