// this file is auto-generated by codegen
// do not modify it directly
import { BoPhan } from '@/lib/generated/prisma'

const API_URL = '/api/bo-phan'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of BoPhan
export async function getListBoPhan(): Promise<ApiResponse<BoPhan[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get BoPhan by idBp
export async function getBoPhan(id: string): Promise<ApiResponse<BoPhan>> {
  try {
    const response = await fetch(`/api/bo-phan/${id}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
// Update BoPhan
export async function updateBoPhan(
  id: string,
  data: Partial<Omit<BoPhan, 'idBp'>>
): Promise<ApiResponse<BoPhan>> {
  try {
    const response = await fetch(`/api/bo-phan/${id}`), {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Delete BoPhan
export async function deleteBoPhan(id: string): Promise<ApiResponse<void>> {
  try {
    const response = await fetch(`/api/bo-phan/${id}`), {
      method: 'DELETE',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new BoPhan
export async function createBoPhan(
  data: Omit<BoPhan, 'idBp'>
): Promise<ApiResponse<BoPhan>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
