// this file is auto-generated by codegen
// do not modify it directly
import { CTKhachO } from '@/lib/generated/prisma'

const API_URL = 'http://localhost:3000/api/c-t-khach-o'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of CTKhachO
export async function getListCTKhachO(): Promise<ApiResponse<CTKhachO[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get list of CTKhachO by ids
export async function getListCTKhachOByIds(ids: string[]): Promise<ApiResponse<CTKhachO[]>> {
  try {
    const response = await fetch(API_URL + '?ids=' + ids.join(','))
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new CTKhachO
export async function createCTKhachO(
  data: Omit<CTKhachO, 'idCtPt' | 'cmnd'>
): Promise<ApiResponse<CTKhachO>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
