// this file is auto-generated by codegen
// do not modify it directly
import { CTTienNghi } from '@/lib/generated/prisma'

const API_URL = 'http://localhost:3000/api/c-t-tien-nghi'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of CTTienNghi
export async function getListCTTienNghi(): Promise<ApiResponse<CTTienNghi[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get list of CTTienNghi by ids
export async function getListCTTienNghiByIds(ids: string[]): Promise<ApiResponse<CTTienNghi[]>> {
  try {
    const response = await fetch(API_URL + '?ids=' + ids.join(','))
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new CTTienNghi
export async function createCTTienNghi(
  data: Omit<CTTienNghi, 'idTn' | 'idHangPhong'>
): Promise<ApiResponse<CTTienNghi>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
