// this file is auto-generated by codegen
// do not modify it directly
import { CTPhuThu } from '@/lib/generated/prisma'

const API_URL = 'http://localhost:3000/api/c-t-phu-thu'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of CTPhuThu
export async function getListCTPhuThu(): Promise<ApiResponse<CTPhuThu[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get list of CTPhuThu by ids
export async function getListCTPhuThuByIds(ids: string[]): Promise<ApiResponse<CTPhuThu[]>> {
  try {
    const response = await fetch(API_URL + '?ids=' + ids.join(','))
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new CTPhuThu
export async function createCTPhuThu(
  data: Omit<CTPhuThu, 'idPhuThu' | 'idCtPt'>
): Promise<ApiResponse<CTPhuThu>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
