// This file is auto-generated by codegen
// Do not modify it directly
import { CTDichVu } from '@/lib/generated/prisma'

const API_URL = '/api/c-t-dich-vu'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of CTDichVu
export async function getListCTDichVu(): Promise<ApiResponse<CTDichVu[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get list of CTDichVu by ids
export async function getListCTDichVuByIds(ids: string[]): Promise<ApiResponse<CTDichVu[]>> {
  try {
    const response = await fetch(`${API_URL}?ids=${ids.join(',')}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new CTDichVu
export async function createCTDichVu(
  data: Omit<CTDichVu, 'idCtpt' | 'idDv' | 'ngaySuDung'>
): Promise<ApiResponse<CTDichVu>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
