// this file is auto-generated by codegen
// do not modify it directly
import { CTPhieuThue } from '@/lib/generated/prisma'

const API_URL = 'http://localhost:3000/api/c-t-phieu-thue'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of CTPhieuThue
export async function getListCTPhieuThue(): Promise<ApiResponse<CTPhieuThue[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get list of CTPhieuThue by ids
export async function getListCTPhieuThueByIds(ids: string[]): Promise<ApiResponse<CTPhieuThue[]>> {
  try {
    const response = await fetch(API_URL + '?ids=' + ids.join(','))
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get CTPhieuThue by idCtPt
export async function getCTPhieuThue(id: string): Promise<ApiResponse<CTPhieuThue>> {
  try {
    const response = await fetch(`http://localhost:3000/api/c-t-phieu-thue/${id}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
// Update CTPhieuThue
export async function updateCTPhieuThue(
  id: string,
  data: Partial<Omit<CTPhieuThue, 'idCtPt'>>
): Promise<ApiResponse<CTPhieuThue>> {
  try {
    const response = await fetch(`http://localhost:3000/api/c-t-phieu-thue/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Delete CTPhieuThue
export async function deleteCTPhieuThue(id: string): Promise<ApiResponse<void>> {
  try {
    const response = await fetch(`http://localhost:3000/api/c-t-phieu-thue/${id}`, {
      method: 'DELETE',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new CTPhieuThue
export async function createCTPhieuThue(
  data: Omit<CTPhieuThue, 'idCtPt'>
): Promise<ApiResponse<CTPhieuThue>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
