// This file is auto-generated by codegen
// Do not modify it directly
import { CTPhieuDat } from '@/lib/generated/prisma'

const API_URL = '/api/c-t-phieu-dat'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of CTPhieuDat
export async function getListCTPhieuDat(): Promise<ApiResponse<CTPhieuDat[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get list of CTPhieuDat by ids
export async function getListCTPhieuDatByIds(ids: string[]): Promise<ApiResponse<CTPhieuDat[]>> {
  try {
    const response = await fetch(`${API_URL}?ids=${ids.join(',')}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new CTPhieuDat
export async function createCTPhieuDat(
  data: Omit<CTPhieuDat, 'idPd' | 'idHp'>
): Promise<ApiResponse<CTPhieuDat>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Update CTPhieuDat by composite key (idPd, idHp)
export async function updateCTPhieuDat(
  idPd: string,
  idHp: string,
  data: Partial<Omit<CTPhieuDat, 'idPd' | 'idHp'>>
): Promise<ApiResponse<CTPhieuDat>> {
  try {
    const response = await fetch(`${API_URL}/update`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ idPd, idHp, ...data }),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
