// this file is auto-generated by codegen
// do not modify it directly
import { CTKhuyenMai } from '@/lib/generated/prisma'

const API_URL = 'http://localhost:3000/api/c-t-khuyen-mai'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of CTKhuyenMai
export async function getListCTKhuyenMai(): Promise<ApiResponse<CTKhuyenMai[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get list of CTKhuyenMai by ids
export async function getListCTKhuyenMaiByIds(ids: string[]): Promise<ApiResponse<CTKhuyenMai[]>> {
  try {
    const response = await fetch(API_URL + '?ids=' + ids.join(','))
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new CTKhuyenMai
export async function createCTKhuyenMai(
  data: Omit<CTKhuyenMai, 'idKm' | 'idHangPhong'>
): Promise<ApiResponse<CTKhuyenMai>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
