// this file is auto-generated by codegen
// do not modify it directly
import { CtDichVu } from '@/lib/generated/prisma'

const API_URL = 'http://localhost:3000/api/ct-dich-vu'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of CtDichVu
export async function getListCtDichVu(): Promise<ApiResponse<CtDichVu[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new CtDichVu
export async function createCtDichVu(
  data: Omit<CtDichVu, 'idCtPt' | 'idDv' | 'ngaySuDung'>
): Promise<ApiResponse<CtDichVu>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
