// this file is auto-generated by codegen
// do not modify it directly
import { CtKhuyenMai } from '@/lib/generated/prisma'

const API_URL = 'http://localhost:3000/api/ct-khuyen-mai'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of CtKhuyenMai
export async function getListCtKhuyenMai(): Promise<ApiResponse<CtKhuyenMai[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new CtKhuyenMai
export async function createCtKhuyenMai(
  data: Omit<CtKhuyenMai, 'idKm' | 'idHangPhong'>
): Promise<ApiResponse<CtKhuyenMai>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
