// this file is auto-generated by codegen
// do not modify it directly
import { CtKhachO } from '@/lib/generated/prisma'

const API_URL = 'http://localhost:3000/api/ct-khach-o'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of CtKhachO
export async function getListCtKhachO(): Promise<ApiResponse<CtKhachO[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new CtKhachO
export async function createCtKhachO(
  data: Omit<CtKhachO, 'idCtPt' | 'cmnd'>
): Promise<ApiResponse<CtKhachO>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
