// this file is auto-generated by codegen
// do not modify it directly
import { CtPhieuDat } from '@/lib/generated/prisma'

const API_URL = '/api/ct-phieu-dat'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of CtPhieuDat
export async function getListCtPhieuDat(): Promise<ApiResponse<CtPhieuDat[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new CtPhieuDat
export async function createCtPhieuDat(
  data: Omit<CtPhieuDat, 'idPd' | 'idHangPhong'>
): Promise<ApiResponse<CtPhieuDat>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
