// this file is auto-generated by codegen
// do not modify it directly
import { CtPhieuThue } from '@/lib/generated/prisma'

const API_URL = '/api/ct-phieu-thue'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of CtPhieuThue
export async function getListCtPhieuThue(): Promise<ApiResponse<CtPhieuThue[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get CtPhieuThue by idCtPt
export async function getCtPhieuThue(id: string): Promise<ApiResponse<CtPhieuThue>> {
  try {
    const response = await fetch(`/api/ct-phieu-thue/${id}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
// Update CtPhieuThue
export async function updateCtPhieuThue(
  id: string,
  data: Partial<Omit<CtPhieuThue, 'idCtPt'>>
): Promise<ApiResponse<CtPhieuThue>> {
  try {
    const response = await fetch(`/api/ct-phieu-thue/${id}`), {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Delete CtPhieuThue
export async function deleteCtPhieuThue(id: string): Promise<ApiResponse<void>> {
  try {
    const response = await fetch(`/api/ct-phieu-thue/${id}`), {
      method: 'DELETE',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new CtPhieuThue
export async function createCtPhieuThue(
  data: Omit<CtPhieuThue, 'idCtPt'>
): Promise<ApiResponse<CtPhieuThue>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
