// this file is auto-generated by codegen
// do not modify it directly
import { CtPhuThu } from '@/lib/generated/prisma'

const API_URL = 'http://localhost:3000/api/ct-phu-thu'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of CtPhuThu
export async function getListCtPhuThu(): Promise<ApiResponse<CtPhuThu[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new CtPhuThu
export async function createCtPhuThu(
  data: Omit<CtPhuThu, 'idPhuThu' | 'idCtPt'>
): Promise<ApiResponse<CtPhuThu>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
