// this file is auto-generated by codegen
// do not modify it directly
import { CtTienNghi } from '@/lib/generated/prisma'

const API_URL = '/api/ct-tien-nghi'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of CtTienNghi
export async function getListCtTienNghi(): Promise<ApiResponse<CtTienNghi[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new CtTienNghi
export async function createCtTienNghi(
  data: Omit<CtTienNghi, 'idTn' | 'idHangPhong'>
): Promise<ApiResponse<CtTienNghi>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
