// this file is auto-generated by codegen
// do not modify it directly
import { DoiPhong } from '@/lib/generated/prisma'

const API_URL = 'http://localhost:3000/api/doi-phong'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of DoiPhong
export async function getListDoiPhong(): Promise<ApiResponse<DoiPhong[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get list of DoiPhong by ids
export async function getListDoiPhongByIds(ids: string[]): Promise<ApiResponse<DoiPhong[]>> {
  try {
    const response = await fetch(API_URL + '?ids=' + ids.join(','))
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new DoiPhong
export async function createDoiPhong(
  data: Omit<DoiPhong, 'idCtPt' | 'soPhongMoi'>
): Promise<ApiResponse<DoiPhong>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
