// This file is auto-generated by codegen
// Do not modify it directly
import { GiaPhuThu } from '@/lib/generated/prisma'

const API_URL = '/api/gia-phu-thu'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of GiaPhuThu
export async function getListGiaPhuThu(): Promise<ApiResponse<GiaPhuThu[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get list of GiaPhuThu by ids
export async function getListGiaPhuThuByIds(ids: string[]): Promise<ApiResponse<GiaPhuThu[]>> {
  try {
    const response = await fetch(`${API_URL}?ids=${ids.join(',')}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new GiaPhuThu
export async function createGiaPhuThu(
  data: Omit<GiaPhuThu, 'idPt' | 'ngayApDung'>
): Promise<ApiResponse<GiaPhuThu>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
