// this file is auto-generated by codegen
// do not modify it directly
import { GiaDichVu } from '@/lib/generated/prisma'

const API_URL = 'http://localhost:3000/api/gia-dich-vu'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of GiaDichVu
export async function getListGiaDichVu(): Promise<ApiResponse<GiaDichVu[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get list of GiaDichVu by ids
export async function getListGiaDichVuByIds(ids: string[]): Promise<ApiResponse<GiaDichVu[]>> {
  try {
    const response = await fetch(API_URL + '?ids=' + ids.join(','))
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new GiaDichVu
export async function createGiaDichVu(
  data: Omit<GiaDichVu, 'idDv' | 'ngayApDung'>
): Promise<ApiResponse<GiaDichVu>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
