// this file is auto-generated by codegen
// do not modify it directly
import { HangPhong } from '@/lib/generated/prisma'

const API_URL = '/api/hang-phong'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of HangPhong
export async function getListHangPhong(): Promise<ApiResponse<HangPhong[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get HangPhong by idHangPhong
export async function getHangPhong(id: string): Promise<ApiResponse<HangPhong>> {
  try {
    const response = await fetch(`/api/hang-phong/${id}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
// Update HangPhong
export async function updateHangPhong(
  id: string,
  data: Partial<Omit<HangPhong, 'idHangPhong'>>
): Promise<ApiResponse<HangPhong>> {
  try {
    const response = await fetch(`/api/hang-phong/${id}`), {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Delete HangPhong
export async function deleteHangPhong(id: string): Promise<ApiResponse<void>> {
  try {
    const response = await fetch(`/api/hang-phong/${id}`), {
      method: 'DELETE',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new HangPhong
export async function createHangPhong(
  data: Omit<HangPhong, 'idHangPhong'>
): Promise<ApiResponse<HangPhong>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
