// this file is auto-generated by codegen
// do not modify it directly
import { HoaDon } from '@/lib/generated/prisma'

const API_URL = '/api/hoa-don'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of HoaDon
export async function getListHoaDon(): Promise<ApiResponse<HoaDon[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get HoaDon by idHd
export async function getHoaDon(id: string): Promise<ApiResponse<HoaDon>> {
  try {
    const response = await fetch(`/api/hoa-don/${id}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
// Update HoaDon
export async function updateHoaDon(
  id: string,
  data: Partial<Omit<HoaDon, 'idHd'>>
): Promise<ApiResponse<HoaDon>> {
  try {
    const response = await fetch(`/api/hoa-don/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Delete HoaDon
export async function deleteHoaDon(id: string): Promise<ApiResponse<void>> {
  try {
    const response = await fetch(`/api/hoa-don/${id}`, {
      method: 'DELETE',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new HoaDon
export async function createHoaDon(
  data: Omit<HoaDon, 'idHd'>
): Promise<ApiResponse<HoaDon>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
