// This file is auto-generated by codegen
// Do not modify it directly
import { KhuyenMai } from '@/lib/generated/prisma'

const API_URL = '/api/khuyen-mai'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of KhuyenMai
export async function getListKhuyenMai(): Promise<ApiResponse<KhuyenMai[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get list of KhuyenMai by ids
export async function getListKhuyenMaiByIds(ids: string[]): Promise<ApiResponse<KhuyenMai[]>> {
  try {
    const response = await fetch(`${API_URL}?ids=${ids.join(',')}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get KhuyenMai by idKm
export async function getKhuyenMai(id: string): Promise<ApiResponse<KhuyenMai>> {
  try {
    const response = await fetch(`${API_URL}/${id}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Update KhuyenMai
export async function updateKhuyenMai(
  id: string,
  data: Partial<Omit<KhuyenMai, 'idKm'>>
): Promise<ApiResponse<KhuyenMai>> {
  try {
    const response = await fetch(`${API_URL}/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Delete KhuyenMai
export async function deleteKhuyenMai(id: string): Promise<ApiResponse<void>> {
  try {
    const response = await fetch(`${API_URL}/${id}`, {
      method: 'DELETE',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new KhuyenMai
export async function createKhuyenMai(
  data: Omit<KhuyenMai, 'idKm'>
): Promise<ApiResponse<KhuyenMai>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
