// this file is auto-generated by codegen
// do not modify it directly
import { KieuPhong } from '@/lib/generated/prisma'

const API_URL = 'http://localhost:3000/api/kieu-phong'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of KieuPhong
export async function getListKieuPhong(): Promise<ApiResponse<KieuPhong[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get KieuPhong by idKp
export async function getKieuPhong(id: string): Promise<ApiResponse<KieuPhong>> {
  try {
    const response = await fetch(`http://localhost:3000/api/kieu-phong/${id}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
// Update KieuPhong
export async function updateKieuPhong(
  id: string,
  data: Partial<Omit<KieuPhong, 'idKp'>>
): Promise<ApiResponse<KieuPhong>> {
  try {
    const response = await fetch(`http://localhost:3000/api/kieu-phong/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Delete KieuPhong
export async function deleteKieuPhong(id: string): Promise<ApiResponse<void>> {
  try {
    const response = await fetch(`http://localhost:3000/api/kieu-phong/${id}`, {
      method: 'DELETE',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new KieuPhong
export async function createKieuPhong(
  data: Omit<KieuPhong, 'idKp'>
): Promise<ApiResponse<KieuPhong>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
