// This file is auto-generated by codegen
// Do not modify it directly
import { LoaiPhong } from '@/lib/generated/prisma'

const API_URL = '/api/loai-phong'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of LoaiPhong
export async function getListLoaiPhong(): Promise<ApiResponse<LoaiPhong[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get list of LoaiPhong by ids
export async function getListLoaiPhongByIds(ids: string[]): Promise<ApiResponse<LoaiPhong[]>> {
  try {
    const response = await fetch(`${API_URL}?ids=${ids.join(',')}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get LoaiPhong by idLp
export async function getLoaiPhong(id: string): Promise<ApiResponse<LoaiPhong>> {
  try {
    const response = await fetch(`${API_URL}/${id}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Update LoaiPhong
export async function updateLoaiPhong(
  id: string,
  data: Partial<Omit<LoaiPhong, 'idLp'>>
): Promise<ApiResponse<LoaiPhong>> {
  try {
    const response = await fetch(`${API_URL}/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Delete LoaiPhong
export async function deleteLoaiPhong(id: string): Promise<ApiResponse<void>> {
  try {
    const response = await fetch(`${API_URL}/${id}`, {
      method: 'DELETE',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new LoaiPhong
export async function createLoaiPhong(
  data: Omit<LoaiPhong, 'idLp'>
): Promise<ApiResponse<LoaiPhong>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
