// this file is auto-generated by codegen
// do not modify it directly
import { NhanVien } from '@/lib/generated/prisma'

const API_URL = '/api/nhan-vien'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of NhanVien
export async function getListNhanVien(): Promise<ApiResponse<NhanVien[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get NhanVien by idNv
export async function getNhanVien(id: string): Promise<ApiResponse<NhanVien>> {
  try {
    const response = await fetch(`/api/nhan-vien/${id}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
// Update NhanVien
export async function updateNhanVien(
  id: string,
  data: Partial<Omit<NhanVien, 'idNv'>>
): Promise<ApiResponse<NhanVien>> {
  try {
    const response = await fetch(`/api/nhan-vien/${id}`), {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Delete NhanVien
export async function deleteNhanVien(id: string): Promise<ApiResponse<void>> {
  try {
    const response = await fetch(`/api/nhan-vien/${id}`), {
      method: 'DELETE',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new NhanVien
export async function createNhanVien(
  data: Omit<NhanVien, 'idNv'>
): Promise<ApiResponse<NhanVien>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
