// This file is auto-generated by codegen
// Do not modify it directly
import { PhieuThue } from '@/lib/generated/prisma'

const API_URL = '/api/phieu-thue'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of PhieuThue
export async function getListPhieuThue(): Promise<ApiResponse<PhieuThue[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get list of PhieuThue by ids
export async function getListPhieuThueByIds(ids: string[]): Promise<ApiResponse<PhieuThue[]>> {
  try {
    const response = await fetch(`${API_URL}?ids=${ids.join(',')}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get PhieuThue by idPt
export async function getPhieuThue(id: string): Promise<ApiResponse<PhieuThue>> {
  try {
    const response = await fetch(`${API_URL}/${id}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Update PhieuThue
export async function updatePhieuThue(
  id: string,
  data: Partial<Omit<PhieuThue, 'idPt'>>
): Promise<ApiResponse<PhieuThue>> {
  try {
    const response = await fetch(`${API_URL}/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Delete PhieuThue
export async function deletePhieuThue(id: string): Promise<ApiResponse<void>> {
  try {
    const response = await fetch(`${API_URL}/${id}`, {
      method: 'DELETE',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new PhieuThue
export async function createPhieuThue(
  data: Omit<PhieuThue, 'idPt'>
): Promise<ApiResponse<PhieuThue>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
