// this file is auto-generated by codegen
// do not modify it directly
import { PhieuDat } from '@/lib/generated/prisma'

const API_URL = 'http://localhost:3000/api/phieu-dat'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of PhieuDat
export async function getListPhieuDat(): Promise<ApiResponse<PhieuDat[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get PhieuDat by idPd
export async function getPhieuDat(id: string): Promise<ApiResponse<PhieuDat>> {
  try {
    const response = await fetch(`http://localhost:3000/api/phieu-dat/${id}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
// Update PhieuDat
export async function updatePhieuDat(
  id: string,
  data: Partial<Omit<PhieuDat, 'idPd'>>
): Promise<ApiResponse<PhieuDat>> {
  try {
    const response = await fetch(`http://localhost:3000/api/phieu-dat/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Delete PhieuDat
export async function deletePhieuDat(id: string): Promise<ApiResponse<void>> {
  try {
    const response = await fetch(`http://localhost:3000/api/phieu-dat/${id}`, {
      method: 'DELETE',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new PhieuDat
export async function createPhieuDat(
  data: Omit<PhieuDat, 'idPd'>
): Promise<ApiResponse<PhieuDat>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
