// This file is auto-generated by codegen
// Do not modify it directly
import { PhuThu } from '@/lib/generated/prisma'

const API_URL = '/api/phu-thu'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of PhuThu
export async function getListPhuThu(): Promise<ApiResponse<PhuThu[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get list of PhuThu by ids
export async function getListPhuThuByIds(ids: string[]): Promise<ApiResponse<PhuThu[]>> {
  try {
    const response = await fetch(`${API_URL}?ids=${ids.join(',')}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Get PhuThu by idPt
export async function getPhuThu(id: string): Promise<ApiResponse<PhuThu>> {
  try {
    const response = await fetch(`${API_URL}/${id}`)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Update PhuThu
export async function updatePhuThu(
  id: string,
  data: Partial<Omit<PhuThu, 'idPt'>>
): Promise<ApiResponse<PhuThu>> {
  try {
    const response = await fetch(`${API_URL}/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Delete PhuThu
export async function deletePhuThu(id: string): Promise<ApiResponse<void>> {
  try {
    const response = await fetch(`${API_URL}/${id}`, {
      method: 'DELETE',
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new PhuThu
export async function createPhuThu(
  data: Omit<PhuThu, 'idPt'>
): Promise<ApiResponse<PhuThu>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
