// this file is auto-generated by codegen
// do not modify it directly
import { QuanLy } from '@/lib/generated/prisma'

const API_URL = '/api/quan-ly'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  message?: string
  error?: string
}

// Get list of QuanLy
export async function getListQuanLy(): Promise<ApiResponse<QuanLy[]>> {
  try {
    const response = await fetch(API_URL)
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Create new QuanLy
export async function createQuanLy(
  data: Omit<QuanLy, 'idBp' | 'manv'>
): Promise<ApiResponse<QuanLy>> {
  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })
    return await response.json()
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}
