// this file is auto-generated by codegen
// do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of CTKhuyenMai
export async function GET(request: NextRequest) {
  try {
		const { searchParams } = new URL(request.url)
    const idsParam = searchParams.get('ids')

		const whereClause = idsParam
      ? { idKm: { in: idsParam.split(',') } }
      : {}

    const cTKhuyenMais = await prisma.cTKhuyenMai.findMany({ where: whereClause })

    return NextResponse.json({
      success: true,
      data: cTKhuyenMais,
    })
  } catch (error) {
    console.error('Error fetching cTKhuyenMai:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new CTKhuyenMai
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newCTKhuyenMai = await prisma.cTKhuyenMai.create({
      data: body,
    })

    return NextResponse.json(
      { success: true, data: newCTKhuyenMai },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating CTKhuyenMai:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
