// this file is auto-generated by codegen
// do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of NhomQuyen
export async function GET(request: NextRequest) {
  try {
    const nhomQuyens = await prisma.nhomQuyen.findMany()
    
    return NextResponse.json({
      success: true,
      data: nhomQuyens,
    })
  } catch (error) {
    console.error('Error fetching nhomQuyen:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new NhomQuyen
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    
    const newNhomQuyen = await prisma.NhomQuyen.create({
      data: body,
    })
    
    return NextResponse.json(
      { success: true, data: newNhomQuyen },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating NhomQuyen:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
