// This file is auto-generated by codegen
// Do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of CTDichVu
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const idsParam = searchParams.get('ids')

    const whereClause = idsParam
      ? { idDv: { in: idsParam.split(',') } }
      : {}

    const cTDichVus = await prisma.cTDichVu.findMany({
      where: whereClause,
      include: {
        cTPhieuThue: true,
        dichVu: true,
        hoaDon: true,
      }
    })

    return NextResponse.json({
      success: true,
      data: cTDichVus,
    })
  } catch (error) {
    console.error('Error fetching cTDichVu:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new CTDichVu
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newCTDichVu = await prisma.cTDichVu.create({
      data: body,
      include: {
        cTPhieuThue: true,
        dichVu: true,
        hoaDon: true,
      }
    })

    return NextResponse.json(
      { success: true, data: newCTDichVu },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating CTDichVu:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
