// This file is auto-generated by codegen
// Do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get single LoaiPhong by idLp
export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params

    const loaiPhong = await prisma.loaiPhong.findUnique({
      where: { idLp: id },
      include: {
        hangPhongs: true,
      }
    })

    if (!loaiPhong) {
      return NextResponse.json(
        { success: false, message: 'Not found' },
        { status: 404 }
      )
    }

    return NextResponse.json({
      success: true,
      data: loaiPhong,
    })
  } catch (error) {
    console.error('Error fetching loaiPhong:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// PUT - Update LoaiPhong by idLp
export async function PUT(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params
    const body = await request.json()

    const updatedLoaiPhong = await prisma.loaiPhong.update({
      where: { idLp: id },
      data: body,
      include: {
        hangPhongs: true,
      }
    })

    return NextResponse.json({
      success: true,
      data: updatedLoaiPhong,
    })
  } catch (error) {
    console.error('Error updating LoaiPhong:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// DELETE - Delete LoaiPhong by idLp
export async function DELETE(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params

    await prisma.loaiPhong.delete({
      where: { idLp: id },
    })

    return NextResponse.json({
      success: true,
      message: 'Deleted successfully',
    })
  } catch (error) {
    console.error('Error deleting loaiPhong:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
