// This file is auto-generated by codegen
// Do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of KhuyenMai
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const idsParam = searchParams.get('ids')

    const whereClause = idsParam
      ? { idKm: { in: idsParam.split(',') } }
      : {}

    const khuyenMais = await prisma.khuyenMai.findMany({
      where: whereClause,
      include: {
        ctKhuyenMais: true,
      }
    })

    return NextResponse.json({
      success: true,
      data: khuyenMais,
    })
  } catch (error) {
    console.error('Error fetching khuyenMai:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new KhuyenMai
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newKhuyenMai = await prisma.khuyenMai.create({
      data: body,
      include: {
        ctKhuyenMais: true,
      }
    })

    return NextResponse.json(
      { success: true, data: newKhuyenMai },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating KhuyenMai:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
