// This file is auto-generated by codegen
// Do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of HoaDon
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const idsParam = searchParams.get('ids')

    const whereClause = idsParam
      ? { idHd: { in: idsParam.split(',') } }
      : {}

    const hoaDons = await prisma.hoaDon.findMany({
      where: whereClause,
      include: {
        nhanVien: true,
        phieuThue: true,
        cTPhieuThues: true,
        cTDichVus: true,
        cTPhuThus: true,
      }
    })

    return NextResponse.json({
      success: true,
      data: hoaDons,
    })
  } catch (error) {
    console.error('Error fetching hoaDon:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new HoaDon
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newHoaDon = await prisma.hoaDon.create({
      data: body,
      include: {
        nhanVien: true,
        phieuThue: true,
        cTPhieuThues: true,
        cTDichVus: true,
        cTPhuThus: true,
      }
    })

    return NextResponse.json(
      { success: true, data: newHoaDon },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating HoaDon:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
