// This file is auto-generated by codegen
// Do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get single CTPhieuThue by idCtpt
export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params

    const cTPhieuThue = await prisma.cTPhieuThue.findUnique({
      where: { idCtpt: id },
      include: {
        phieuThue: true,
        phong: true,
        hoaDon: true,
        cTKhachOs: true,
        doiPhongs: true,
      }
    })

    if (!cTPhieuThue) {
      return NextResponse.json(
        { success: false, message: 'Not found' },
        { status: 404 }
      )
    }

    return NextResponse.json({
      success: true,
      data: cTPhieuThue,
    })
  } catch (error) {
    console.error('Error fetching cTPhieuThue:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// PUT - Update CTPhieuThue by idCtpt
export async function PUT(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params
    const body = await request.json()

    const updatedCTPhieuThue = await prisma.cTPhieuThue.update({
      where: { idCtpt: id },
      data: body,
      include: {
        phieuThue: true,
        phong: true,
        hoaDon: true,
        cTKhachOs: true,
        doiPhongs: true,
      }
    })

    return NextResponse.json({
      success: true,
      data: updatedCTPhieuThue,
    })
  } catch (error) {
    console.error('Error updating CTPhieuThue:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// DELETE - Delete CTPhieuThue by idCtpt
export async function DELETE(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params

    await prisma.cTPhieuThue.delete({
      where: { idCtpt: id },
    })

    return NextResponse.json({
      success: true,
      message: 'Deleted successfully',
    })
  } catch (error) {
    console.error('Error deleting cTPhieuThue:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
