// this file is auto-generated by codegen
// do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of CtDichVu
export async function GET(request: NextRequest) {
  try {
    const ctDichVus = await prisma.CtDichVu.findMany()
    
    return NextResponse.json({
      success: true,
      data: ctDichVus,
    })
  } catch (error) {
    console.error('Error fetching ctDichVu:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new CtDichVu
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    
    const newCtDichVu = await prisma.CtDichVu.create({
      data: body,
    })
    
    return NextResponse.json(
      { success: true, data: newCtDichVu },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating CtDichVu:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
