// This file is auto-generated by codegen
// Do not modify it directly
'use client'

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { login, register, logout, getCurrentUser } from '@/lib/services/auth.service'
import type { LoginRequest, RegisterRequest } from '@/lib/services/auth.service'

// Get current user
export function useCurrentUser() {
  return useQuery({
    queryKey: ['currentUser'],
    queryFn: getCurrentUser,
    retry: false,
  })
}

// Login mutation
export function useLogin() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (credentials: LoginRequest) => login(credentials),
    onSuccess: (data) => {
      if (data.success) {
        queryClient.setQueryData(['currentUser'], data)
        queryClient.invalidateQueries({ queryKey: ['currentUser'] })
      }
    },
  })
}

// Register mutation
export function useRegister() {
  return useMutation({
    mutationFn: (data: RegisterRequest) => register(data),
  })
}

// Logout mutation
export function useLogout() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: logout,
    onSuccess: () => {
      queryClient.setQueryData(['currentUser'], null)
      queryClient.invalidateQueries({ queryKey: ['currentUser'] })
    },
  })
}

// Auth context hook helper
export function useAuth() {
  const { data, isLoading } = useCurrentUser()
  const loginMutation = useLogin()
  const logoutMutation = useLogout()

  return {
    user: data?.data?.user,
    isAuthenticated: data?.success ?? false,
    isLoading,
    login: loginMutation.mutate,
    logout: logoutMutation.mutate,
    isLoggingIn: loginMutation.isPending,
    isLoggingOut: logoutMutation.isPending,
  }
}
