// This file is auto-generated by codegen
// Do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of KhachHang
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const idsParam = searchParams.get('ids')

    const whereClause = idsParam
      ? { idKh: { in: idsParam.split(',') } }
      : {}

    const khachHangs = await prisma.khachHang.findMany({
      where: whereClause,
      
    })

    return NextResponse.json({
      success: true,
      data: khachHangs,
    })
  } catch (error) {
    console.error('Error fetching khachHang:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new KhachHang
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newKhachHang = await prisma.khachHang.create({
      data: body,
      
    })

    return NextResponse.json(
      { success: true, data: newKhachHang },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating KhachHang:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
