// This file is auto-generated by codegen
// Do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get single DichVu by idDv
export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params

    const dichVu = await prisma.dichVu.findUnique({
      where: { idDv: id },
      include: {
        giaDichVus: true,
        ctDichVus: true,
      }
    })

    if (!dichVu) {
      return NextResponse.json(
        { success: false, message: 'Not found' },
        { status: 404 }
      )
    }

    return NextResponse.json({
      success: true,
      data: dichVu,
    })
  } catch (error) {
    console.error('Error fetching dichVu:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// PUT - Update DichVu by idDv
export async function PUT(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params
    const body = await request.json()

    const updatedDichVu = await prisma.dichVu.update({
      where: { idDv: id },
      data: body,
      include: {
        giaDichVus: true,
        ctDichVus: true,
      }
    })

    return NextResponse.json({
      success: true,
      data: updatedDichVu,
    })
  } catch (error) {
    console.error('Error updating DichVu:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// DELETE - Delete DichVu by idDv
export async function DELETE(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params

    await prisma.dichVu.delete({
      where: { idDv: id },
    })

    return NextResponse.json({
      success: true,
      message: 'Deleted successfully',
    })
  } catch (error) {
    console.error('Error deleting dichVu:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
