// This file is auto-generated by codegen
// Do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import bcrypt from 'bcryptjs'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { username, password, email, ho, ten, sdt, idBp, idNq } = body

    // Validate required fields
    if (!username || !password || !email || !ho || !ten) {
      return NextResponse.json(
        { success: false, message: 'Missing required fields' },
        { status: 400 }
      )
    }

    // Check if username exists
    const existingUser = await prisma.nhanVien.findUnique({
      where: { username },
    })

    if (existingUser) {
      return NextResponse.json(
        { success: false, message: 'Username already exists' },
        { status: 400 }
      )
    }

    // Check if email exists
    const existingEmail = await prisma.nhanVien.findUnique({
      where: { email },
    })

    if (existingEmail) {
      return NextResponse.json(
        { success: false, message: 'Email already exists' },
        { status: 400 }
      )
    }

    // Hash password
    const hashedPassword = await bcrypt.hash(password, 10)

    // Generate ID
    const idNv = 'NV' + Date.now().toString().slice(-8)

    // Create user
    const newUser = await prisma.nhanVien.create({
      data: {
        idNv,
        username,
        password: hashedPassword,
        email,
        ho,
        ten,
        sdt: sdt || '',
        idBp: idBp || 'BP01', // Default bộ phận
        idNq: idNq || 'NQ02', // Default nhóm quyền (staff)
      },
      include: {
        boPhan: true,
        nhomQuyen: true,
      },
    })

    // Remove password from response
    const { password: _, ...userWithoutPassword } = newUser

    return NextResponse.json(
      {
        success: true,
        data: userWithoutPassword,
        message: 'Registration successful',
      },
      { status: 201 }
    )
  } catch (error) {
    console.error('Register error:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
