// This file is auto-generated by codegen
// Do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of DichVu
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const idsParam = searchParams.get('ids')

    const whereClause = idsParam
      ? { idDv: { in: idsParam.split(',') } }
      : {}

    const dichVus = await prisma.dichVu.findMany({
      where: whereClause,
      include: {
        giaDichVus: true,
        ctDichVus: true,
      }
    })

    return NextResponse.json({
      success: true,
      data: dichVus,
    })
  } catch (error) {
    console.error('Error fetching dichVu:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new DichVu
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newDichVu = await prisma.dichVu.create({
      data: body,
      include: {
        giaDichVus: true,
        ctDichVus: true,
      }
    })

    return NextResponse.json(
      { success: true, data: newDichVu },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating DichVu:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
