// this file is auto-generated by codegen
// do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of CtPhieuDat
export async function GET(request: NextRequest) {
  try {
    const ctPhieuDats = await prisma.CtPhieuDat.findMany()

    return NextResponse.json({
      success: true,
      data: ctPhieuDats,
    })
  } catch (error) {
    console.error('Error fetching ctPhieuDat:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new CtPhieuDat
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newCtPhieuDat = await prisma.CtPhieuDat.create({
      data: body,
    })

    return NextResponse.json(
      { success: true, data: newCtPhieuDat },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating CtPhieuDat:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
