// This file is auto-generated by codegen
// Do not modify it directly
import type { NhanVien, BoPhan, NhomQuyen } from '@/lib/generated/prisma'

export type AuthUser = Omit<NhanVien, 'password'> & {
  boPhan: BoPhan
  nhomQuyen: NhomQuyen
}

export interface AuthState {
  user: AuthUser | null
  isAuthenticated: boolean
  isLoading: boolean
}
