// This file is auto-generated by codegen
// Do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of CTTienNghi
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const idsParam = searchParams.get('ids')

    const whereClause = idsParam
      ? { idTn: { in: idsParam.split(',') } }
      : {}

    const cTTienNghis = await prisma.cTTienNghi.findMany({
      where: whereClause,
      include: {
        tienNghi: true,
        hangPhong: true,
      }
    })

    return NextResponse.json({
      success: true,
      data: cTTienNghis,
    })
  } catch (error) {
    console.error('Error fetching cTTienNghi:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new CTTienNghi
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newCTTienNghi = await prisma.cTTienNghi.create({
      data: body,
      include: {
        tienNghi: true,
        hangPhong: true,
      }
    })

    return NextResponse.json(
      { success: true, data: newCTTienNghi },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating CTTienNghi:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
