// this file is auto-generated by codegen
// do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of CTPhieuThue
export async function GET(request: NextRequest) {
  try {
		const { searchParams } = new URL(request.url)
    const idsParam = searchParams.get('ids')

		const whereClause = idsParam
      ? { idPt: { in: idsParam.split(',') } }
      : {}

    const cTPhieuThues = await prisma.cTPhieuThue.findMany({ where: whereClause })

    return NextResponse.json({
      success: true,
      data: cTPhieuThues,
    })
  } catch (error) {
    console.error('Error fetching cTPhieuThue:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new CTPhieuThue
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newCTPhieuThue = await prisma.cTPhieuThue.create({
      data: body,
    })

    return NextResponse.json(
      { success: true, data: newCTPhieuThue },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating CTPhieuThue:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
