// This file is auto-generated by codegen
// Do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of PhieuThue
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const idsParam = searchParams.get('ids')

    const whereClause = idsParam
      ? { idPt: { in: idsParam.split(',') } }
      : {}

    const phieuThues = await prisma.phieuThue.findMany({
      where: whereClause,
      include: {
        nhanVien: true,
        khachHang: true,
        phieuDat: true,
        hoaDons: true,
        cTPhieuThues: true,
      }
    })

    return NextResponse.json({
      success: true,
      data: phieuThues,
    })
  } catch (error) {
    console.error('Error fetching phieuThue:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new PhieuThue
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newPhieuThue = await prisma.phieuThue.create({
      data: body,
      include: {
        nhanVien: true,
        khachHang: true,
        phieuDat: true,
        hoaDons: true,
        cTPhieuThues: true,
      }
    })

    return NextResponse.json(
      { success: true, data: newPhieuThue },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating PhieuThue:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
