// this file is auto-generated by codegen
// do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of CtPhieuThue
export async function GET(request: NextRequest) {
  try {
    const ctPhieuThues = await prisma.CtPhieuThue.findMany()
    
    return NextResponse.json({
      success: true,
      data: ctPhieuThues,
    })
  } catch (error) {
    console.error('Error fetching ctPhieuThue:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new CtPhieuThue
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    
    const newCtPhieuThue = await prisma.CtPhieuThue.create({
      data: body,
    })
    
    return NextResponse.json(
      { success: true, data: newCtPhieuThue },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating CtPhieuThue:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
