// This file is auto-generated by codegen
// Do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of CTPhuThu
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const idsParam = searchParams.get('ids')

    const whereClause = idsParam
      ? { idPt: { in: idsParam.split(',') } }
      : {}

    const cTPhuThus = await prisma.cTPhuThu.findMany({
      where: whereClause,
      include: {
        phuThu: true,
        cTPhieuThue: true,
        hoaDon: true,
      }
    })

    return NextResponse.json({
      success: true,
      data: cTPhuThus,
    })
  } catch (error) {
    console.error('Error fetching cTPhuThu:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new CTPhuThu
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newCTPhuThu = await prisma.cTPhuThu.create({
      data: body,
      include: {
        phuThu: true,
        cTPhieuThue: true,
        hoaDon: true,
      }
    })

    return NextResponse.json(
      { success: true, data: newCTPhuThu },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating CTPhuThu:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
