// this file is auto-generated by codegen
// do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of CtTienNghi
export async function GET(request: NextRequest) {
  try {
    const ctTienNghis = await prisma.ctTienNghi.findMany()

    return NextResponse.json({
      success: true,
      data: ctTienNghis,
    })
  } catch (error) {
    console.error('Error fetching ctTienNghi:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new CtTienNghi
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newCtTienNghi = await prisma.ctTienNghi.create({
      data: body,
    })

    return NextResponse.json(
      { success: true, data: newCtTienNghi },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating CtTienNghi:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
