// this file is auto-generated by codegen
// do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of CtKhuyenMai
export async function GET(request: NextRequest) {
  try {
    const ctKhuyenMais = await prisma.CtKhuyenMai.findMany()
    
    return NextResponse.json({
      success: true,
      data: ctKhuyenMais,
    })
  } catch (error) {
    console.error('Error fetching ctKhuyenMai:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new CtKhuyenMai
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    
    const newCtKhuyenMai = await prisma.CtKhuyenMai.create({
      data: body,
    })
    
    return NextResponse.json(
      { success: true, data: newCtKhuyenMai },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating CtKhuyenMai:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
