// this file is auto-generated by codegen
// do not modify it directly
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get list of CtKhachO
export async function GET(request: NextRequest) {
  try {
    const ctKhachOs = await prisma.ctKhachO.findMany()

    return NextResponse.json({
      success: true,
      data: ctKhachOs,
    })
  } catch (error) {
    console.error('Error fetching ctKhachO:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST - Create new CtKhachO
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newCtKhachO = await prisma.ctKhachO.create({
      data: body,
    })

    return NextResponse.json(
      { success: true, data: newCtKhachO },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating CtKhachO:', error)
    return NextResponse.json(
      { success: false, message: 'Internal server error' },
      { status: 500 }
    )
  }
}
